### PR TITLE
Create empty activity for the home page of the app

### PR DESCRIPTION
**Pull request by sidney-prytherch**
Pull Request for home page activity

### CODE REVIEW

**Comment by sidney-prytherch** [comment]
[Make Home Page dummy](https://trello.com/c/T123sHJu/26-make-home-page-dummy)

**Comment by sidney-prytherch** [comment]
[Initialize Project](https://trello.com/c/imNmwV3P/22-initialize-project)

**Review by HirdrWit — APPROVED** [review]
Looks good my duud

**Review by HirdrWit — APPROVED** [review]

**Review by HirdrWit — APPROVED** [review]

**Comment by HirdrWit** [comment]
It won't let me merge!!! ABORT

**Comment by sidney-prytherch** [comment]
lmao

**Comment by sidney-prytherch** [comment]
I think I got the wrong account for you. Hang on...

**Pull request merged**
